-- PaeCal2 migration: brand/product food presets + drink sweetness levels
-- Run this in Supabase SQL Editor. Safe to re-run.
-- Values in this seed are estimate presets for speed/cost reduction.
-- Mark verified=true only after checking against label/official nutrition.

create table if not exists public.brand_food_presets (
  preset_key text primary key,
  brand text not null,
  product_name text not null,
  menu_name text not null,
  category text not null default 'general',
  serving_size text not null default '1 serving',
  kcal numeric not null default 0,
  carb numeric not null default 0,
  protein numeric not null default 0,
  fat numeric not null default 0,
  sugar numeric not null default 0,
  sweetness_level integer,
  aliases text[] not null default '{}'::text[],
  source_type text not null default 'estimate_seed',
  source_note text,
  confidence text not null default 'medium',
  status text not null default 'active',
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists brand_food_presets_brand_idx
  on public.brand_food_presets (brand);

create index if not exists brand_food_presets_category_idx
  on public.brand_food_presets (category);

create index if not exists brand_food_presets_aliases_gin_idx
  on public.brand_food_presets using gin (aliases);

create table if not exists public.drink_sweetness_levels (
  drink_key text not null,
  menu_name text not null,
  sweetness_level integer not null check (sweetness_level in (0, 25, 50, 75, 100)),
  kcal numeric not null default 0,
  carb numeric not null default 0,
  protein numeric not null default 0,
  fat numeric not null default 0,
  sugar numeric not null default 0,
  source_type text not null default 'estimate_seed',
  source_note text,
  confidence text not null default 'medium',
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (drink_key, sweetness_level)
);

create index if not exists drink_sweetness_levels_menu_idx
  on public.drink_sweetness_levels (menu_name);

insert into public.brand_food_presets (
  preset_key, brand, product_name, menu_name, category, serving_size,
  kcal, carb, protein, fat, sugar, sweetness_level, aliases,
  source_type, source_note, confidence, status, verified
) values
  ('lay_s_classic_20g','Lay''s','Classic 20g','เลย์รสดั้งเดิม 20g','snack','1 small bag',110,13,2,7,1,NULL,ARRAY['เลย์','เลย์ห่อ20','เลย์รสดั้งเดิม','lays']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('lay_s_nori_seaweed_20g','Lay''s','Nori Seaweed 20g','เลย์โนริสาหร่าย 20g','snack','1 small bag',110,13,2,7,1,NULL,ARRAY['เลย์โนริ','เลย์สาหร่าย','เลย์ห่อเขียว']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('lay_s_bbq_20g','Lay''s','BBQ 20g','เลย์บาร์บีคิว 20g','snack','1 small bag',110,13,2,7,2,NULL,ARRAY['เลย์บาร์บีคิว','เลย์บีบีคิว']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('tasto_potato_chips_20g','Tasto','Potato chips 20g','เทสโต 20g','snack','1 small bag',110,13,2,7,1,NULL,ARRAY['เทสโต','tasto']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('pringles_original_small_can','Pringles','Original small can','พริงเกิลส์กระป๋องเล็ก','snack','1 small can',210,22,3,13,1,NULL,ARRAY['พริงเกิลส์','pringles']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('potae_corn_snack_small','Potae','Corn snack small','โปเต้ซองเล็ก','snack','1 small bag',120,18,2,5,2,NULL,ARRAY['โปเต้','potae']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('cornae_corn_snack_small','Cornae','Corn snack small','คอร์นเน่ซองเล็ก','snack','1 small bag',120,18,2,5,2,NULL,ARRAY['คอร์นเน่','cornae']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('tao_kae_noi_crispy_seaweed_small','Tao Kae Noi','Crispy seaweed small','เถ้าแก่น้อยซองเล็ก','snack','1 small bag',80,8,2,5,1,NULL,ARRAY['เถ้าแก่น้อย','สาหร่ายเถ้าแก่น้อย']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('pocky_chocolate_box','Pocky','Chocolate box','ป๊อกกี้ช็อกโกแลต','snack','1 box',220,32,4,9,18,NULL,ARRAY['ป๊อกกี้','pocky']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('pretz_original_box','Pretz','Original box','เพรทซ์','snack','1 box',180,28,5,6,4,NULL,ARRAY['เพรทซ์','pretz']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('oreo_small_pack','Oreo','Small pack','โอริโอซองเล็ก','snack','1 pack',260,38,3,11,22,NULL,ARRAY['โอริโอ','oreo']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('kitkat_regular_bar','KitKat','Regular bar','คิทแคทแท่ง','snack','1 bar',220,28,3,11,21,NULL,ARRAY['คิทแคท','kitkat']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('m_m_s_milk_chocolate_small','M&M''s','Milk chocolate small','เอ็มแอนด์เอ็มซองเล็ก','snack','1 small bag',240,34,3,10,28,NULL,ARRAY['m&m','เอ็มแอนด์เอ็ม']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('snickers_regular_bar','Snickers','Regular bar','สนิกเกอร์แท่ง','snack','1 bar',250,33,5,12,27,NULL,ARRAY['snickers','สนิกเกอร์']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('hershey_s_milk_chocolate_bar','Hershey''s','Milk chocolate bar','เฮอร์ชีส์ช็อกโกแลต','snack','1 bar',220,26,3,13,24,NULL,ARRAY['hershey','เฮอร์ชีส์']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('potato_corner_cheese_regular','Potato Corner','Cheese regular','โปเตโต้คอร์เนอร์ชีสไซซ์ปกติ','snack','regular',320,38,5,17,2,NULL,ARRAY['โปเตโต้คอร์เนอร์','potato corner','ชีส']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('potato_corner_bbq_regular','Potato Corner','BBQ regular','โปเตโต้คอร์เนอร์บาร์บีคิวไซซ์ปกติ','snack','regular',320,38,5,17,2,NULL,ARRAY['potato corner bbq','โปเตโต้คอร์เนอร์บาร์บีคิว']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('chatramue_thai_tea_75','ChaTraMue','Thai tea 75%','ชาไทยชาตรามือหวานปกติ','drink','1 cup',220,35,3,6,30,75,ARRAY['ชาตรามือ','ชาไทยชาตรามือ']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('chatramue_green_tea_75','ChaTraMue','Green tea 75%','ชาเขียวชาตรามือหวานปกติ','drink','1 cup',220,35,4,6,30,75,ARRAY['ชาเขียวชาตรามือ']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('oishi_green_tea_honey_lemon','Oishi','Green Tea Honey Lemon','โออิชิกรีนทีฮันนี่เลมอน','drink','1 bottle',160,40,0,0,36,NULL,ARRAY['โออิชิฮันนี่เลมอน','oishi honey lemon']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('oishi_green_tea_original','Oishi','Green Tea Original','โออิชิกรีนทีต้นตำรับ','drink','1 bottle',140,34,0,0,30,NULL,ARRAY['โออิชิ','oishi']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('ichitan_green_tea_original','Ichitan','Green Tea Original','อิชิตันกรีนทีต้นตำรับ','drink','1 bottle',140,34,0,0,30,NULL,ARRAY['อิชิตัน','ichitan']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('coke_original_can','Coke','Original can','โค้กกระป๋อง','drink','1 can',140,35,0,0,35,NULL,ARRAY['โค้ก','coke']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('coke_zero_can','Coke','Zero can','โค้กซีโร่','drink','1 can',0,0,0,0,0,NULL,ARRAY['โค้กซีโร่','coke zero']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('pepsi_original_can','Pepsi','Original can','เป๊ปซี่กระป๋อง','drink','1 can',140,35,0,0,35,NULL,ARRAY['เป๊ปซี่','pepsi']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('pepsi_max_can','Pepsi','Max can','เป๊ปซี่แมกซ์','drink','1 can',0,0,0,0,0,NULL,ARRAY['เป๊ปซี่แมกซ์','pepsi max']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('sprite_can','Sprite','Can','สไปรท์กระป๋อง','drink','1 can',140,35,0,0,35,NULL,ARRAY['สไปรท์','sprite']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('fanta_red_can','Fanta','Red can','แฟนต้าน้ำแดง','drink','1 can',160,40,0,0,40,NULL,ARRAY['แฟนต้า','น้ำแดงแฟนต้า']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('birdy_ready_coffee_can','Birdy','Ready coffee can','เบอร์ดี้กาแฟกระป๋อง','drink','1 can',110,18,2,3,16,NULL,ARRAY['เบอร์ดี้','birdy']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('nescafe_3_in_1_sachet','Nescafe','3 in 1 sachet','เนสกาแฟทรีอินวัน 1 ซอง','drink','1 sachet',90,14,1,3,10,NULL,ARRAY['เนสกาแฟซอง','เนสกาแฟ 3in1','nescafe 3 in 1']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('nescafe_americano_can','Nescafe','Americano can','เนสกาแฟอเมริกาโน่กระป๋อง','drink','1 can',50,10,1,0,8,NULL,ARRAY['เนสกาแฟอเมริกาโน่']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('cafe_amazon_iced_americano','Cafe Amazon','Iced Americano','อเมริกาโน่เย็นคาเฟ่อเมซอน','drink','1 cup',20,3,1,0,0,NULL,ARRAY['อเมซอนอเมริกาโน่','กาแฟอเมซอน']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('cafe_amazon_iced_latte','Cafe Amazon','Iced Latte','ลาเต้เย็นคาเฟ่อเมซอน','drink','1 cup',180,18,8,8,14,NULL,ARRAY['อเมซอนลาเต้']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('all_cafe_iced_americano','All Cafe','Iced Americano','อเมริกาโน่เย็นออลคาเฟ่','drink','1 cup',20,3,1,0,0,NULL,ARRAY['ออลคาเฟ่','all cafe']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('all_cafe_iced_latte','All Cafe','Iced Latte','ลาเต้เย็นออลคาเฟ่','drink','1 cup',180,18,8,8,14,NULL,ARRAY['ออลคาเฟ่ลาเต้']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('inthanin_iced_americano','Inthanin','Iced Americano','อเมริกาโน่เย็นอินทนิล','drink','1 cup',20,3,1,0,0,NULL,ARRAY['อินทนิลอเมริกาโน่']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('punthai_iced_latte','Punthai','Iced Latte','ลาเต้เย็นพันธุ์ไทย','drink','1 cup',180,18,8,8,14,NULL,ARRAY['พันธุ์ไทยลาเต้']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('starbucks_caffe_latte_tall','Starbucks','Caffe Latte tall','สตาร์บัคส์ลาเต้ทอล','drink','tall',190,18,10,7,17,NULL,ARRAY['starbucks latte','สตาร์บัคส์ลาเต้']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('meiji_pasteurized_milk_plain','Meiji','Pasteurized milk plain','นมเมจิจืด','drink','1 bottle',160,12,8,8,12,NULL,ARRAY['เมจิ','นมเมจิ']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('dutch_mill_drinking_yogurt_small','Dutch Mill','Drinking yogurt small','ดัชมิลล์โยเกิร์ตพร้อมดื่ม','drink','1 bottle',160,28,5,3,24,NULL,ARRAY['ดัชมิลล์','dutch mill']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('dutchie_yogurt_cup','Dutchie','Yogurt cup','โยเกิร์ตดัชชี่','dairy','1 cup',120,18,5,3,16,NULL,ARRAY['ดัชชี่','dutchie']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('foremost_plain_milk','Foremost','Plain milk','นมโฟร์โมสต์จืด','drink','1 carton',150,12,8,8,12,NULL,ARRAY['โฟร์โมสต์','foremost']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('cp_boiled_egg_pack','CP','Boiled egg pack','ไข่ต้มซีพี','convenience','2 eggs',160,1,13,11,0,NULL,ARRAY['ไข่ต้ม cp','ไข่ต้มซีพี']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('cp_chicken_breast','CP','Chicken breast','อกไก่ซีพี','convenience','1 pack',120,2,24,2,1,NULL,ARRAY['อกไก่ cp','อกไก่ซีพี']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('betagro_chicken_breast','Betagro','Chicken breast','อกไก่เบทาโกร','convenience','1 pack',120,2,24,2,1,NULL,ARRAY['อกไก่เบทาโกร']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('ezygo_krapao_rice','EZYGO','Krapao rice','ข้าวกะเพราอีซี่โก','convenience','1 pack',520,70,20,18,6,NULL,ARRAY['ezygo กะเพรา','อีซี่โกกะเพรา']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('ezygo_fried_rice','EZYGO','Fried rice','ข้าวผัดอีซี่โก','convenience','1 pack',520,75,16,16,6,NULL,ARRAY['ezygo ข้าวผัด']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('7_select_sandwich_ham_cheese','7-Select','Sandwich ham cheese','แซนด์วิชแฮมชีสเซเว่น','convenience','1 pack',300,36,14,12,6,NULL,ARRAY['แซนด์วิชเซเว่น','แฮมชีสเซเว่น']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('7_select_onigiri_tuna','7-Select','Onigiri tuna','โอนิกิริทูน่าเซเว่น','convenience','1 piece',220,38,8,4,3,NULL,ARRAY['โอนิกิริ','ข้าวปั้นเซเว่น']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('swensen_s_rainbow_sherbet_scoop','Swensen''s','Rainbow sherbet scoop','ไอติมเรนโบว์เชอร์เบท','dessert','1 scoop',130,28,1,2,24,NULL,ARRAY['ไอติมเรนโบว์','rainbow sherbet']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('swensen_s_chocolate_scoop','Swensen''s','Chocolate scoop','ไอติมช็อกโกแลตสเวนเซ่นส์','dessert','1 scoop',180,22,4,9,18,NULL,ARRAY['สเวนเซ่นส์ช็อกโกแลต']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('dairy_queen_oreo_blizzard_mini','Dairy Queen','Oreo Blizzard mini','แดรี่ควีนบลิซซาร์ดโอริโอ้มินิ','dessert','mini',350,52,8,12,40,NULL,ARRAY['dq blizzard','บลิซซาร์ดโอริโอ้']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('dairy_queen_cone','Dairy Queen','Cone','ไอติมโคนแดรี่ควีน','dessert','1 cone',220,34,5,7,24,NULL,ARRAY['ไอติมโคน dq','แดรี่ควีนโคน']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('wall_s_cornetto','Wall''s','Cornetto','คอร์เนตโต้','dessert','1 cone',220,28,4,10,20,NULL,ARRAY['cornetto','คอร์เนตโต']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('nestle_extreme_ice_cream','Nestle','Extreme ice cream','เนสท์เล่เอ็กซ์ตรีม','dessert','1 cone',230,30,4,10,22,NULL,ARRAY['เอ็กซ์ตรีม','nestle extreme']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('mcdonald_s_french_fries_medium','McDonald''s','French fries medium','เฟรนช์ฟรายส์แมคกลาง','fast_food','medium',340,44,4,16,0,NULL,ARRAY['เฟรนฟรายแมค','แมคเฟรนฟราย']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('mcdonald_s_cheeseburger','McDonald''s','Cheeseburger','ชีสเบอร์เกอร์แมค','fast_food','1 burger',300,33,15,13,7,NULL,ARRAY['ชีสเบอร์เกอร์แมค']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('kfc_fried_chicken_1_pc','KFC','Fried chicken 1 pc','ไก่ทอดเคเอฟซี 1 ชิ้น','fast_food','1 piece',280,10,20,18,1,NULL,ARRAY['ไก่ kfc','เคเอฟซี']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('kfc_french_fries_regular','KFC','French fries regular','เฟรนช์ฟรายส์เคเอฟซี','fast_food','regular',300,38,4,15,0,NULL,ARRAY['เฟรนฟราย kfc']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('burger_king_whopper','Burger King','Whopper','วอปเปอร์เบอร์เกอร์คิง','fast_food','1 burger',650,50,28,38,10,NULL,ARRAY['whopper','วอปเปอร์']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('pizza_hut_hawaiian_slice','Pizza Hut','Hawaiian slice','พิซซ่าฮาวายเอี้ยน 1 ชิ้น','fast_food','1 slice',280,34,12,10,5,NULL,ARRAY['พิซซ่าฮัทฮาวายเอี้ยน']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('the_pizza_company_seafood_slice','The Pizza Company','Seafood slice','พิซซ่าซีฟู้ด 1 ชิ้น','fast_food','1 slice',300,34,13,12,5,NULL,ARRAY['พิซซ่าคอมปะนี','the pizza company']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('domino_s_pepperoni_slice','Domino''s','Pepperoni slice','โดมิโน่เปปเปอโรนี 1 ชิ้น','fast_food','1 slice',300,32,12,14,3,NULL,ARRAY['โดมิโน่','domino']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('chester_s_grilled_chicken_rice','Chester''s','Grilled chicken rice','ข้าวไก่ย่างเชสเตอร์','fast_food','1 plate',560,70,32,14,8,NULL,ARRAY['เชสเตอร์','chester']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('bonchon_chicken_wings_small','Bonchon','Chicken wings small','บอนชอนไก่ทอดชุดเล็ก','fast_food','small',600,45,35,30,12,NULL,ARRAY['บอนชอน','bonchon']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('yayoi_chicken_teriyaki_set','Yayoi','Chicken teriyaki set','ยาโยอิไก่เทอริยากิ','restaurant','1 set',650,85,32,18,14,NULL,ARRAY['ยาโยอิ','yayoi']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('fuji_salmon_teriyaki_set','Fuji','Salmon teriyaki set','ฟูจิแซลมอนเทอริยากิ','restaurant','1 set',650,80,35,20,12,NULL,ARRAY['ฟูจิ','fuji']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('sushiro_salmon_sushi_2_pcs','Sushiro','Salmon sushi 2 pcs','ซูชิโร่แซลมอน 2 คำ','restaurant','2 pcs',120,18,8,3,2,NULL,ARRAY['ซูชิโร่แซลมอน','sushiro salmon']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('hachiban_ramen_bowl','Hachiban','Ramen bowl','ฮะจิบังราเมง','restaurant','1 bowl',520,70,22,16,6,NULL,ARRAY['ฮะจิบัง','hachiban']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('mk_suki_set','MK','Suki set','เอ็มเคสุกี้ชุดเล็ก','restaurant','1 set',500,45,35,18,8,NULL,ARRAY['mk สุกี้','เอ็มเค']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('shabushi_buffet_estimate','Shabushi','Buffet estimate','ชาบูชิบุฟเฟต์','restaurant','1 meal',900,80,45,45,18,NULL,ARRAY['ชาบูชิ','shabushi']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('s_p_butter_cake_slice','S&P','Butter cake slice','เอสแอนด์พีบัตเตอร์เค้ก','dessert','1 slice',280,32,5,14,20,NULL,ARRAY['s&p cake','เค้กเอสแอนด์พี']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('after_you_shibuya_honey_toast','After You','Shibuya honey toast','อาฟเตอร์ยูฮันนี่โทสต์','dessert','1 serving',900,110,14,42,70,NULL,ARRAY['after you','ฮันนี่โทสต์']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('krispy_kreme_original_glazed_donut','Krispy Kreme','Original glazed donut','คริสปี้ครีมออริจินัล','dessert','1 donut',200,22,3,11,10,NULL,ARRAY['คริสปี้ครีม','krispy kreme']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('dunkin_donut_regular','Dunkin''','Donut regular','ดังกิ้นโดนัท','dessert','1 donut',230,30,4,11,14,NULL,ARRAY['ดังกิ้น','dunkin']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('mister_donut_pon_de_ring','Mister Donut','Pon de ring','มิสเตอร์โดนัทพอนเดอริง','dessert','1 piece',230,28,3,12,14,NULL,ARRAY['มิสเตอร์โดนัท','พอนเดอริง']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('yamazaki_melon_pan','Yamazaki','Melon pan','ยามาซากิเมล่อนปัง','bakery','1 piece',320,48,7,10,18,NULL,ARRAY['ยามาซากิ','melon pan']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('breadtalk_floss_bun','BreadTalk','Floss bun','เบรดทอล์คขนมปังหมูหยอง','bakery','1 piece',320,42,10,12,10,NULL,ARRAY['breadtalk','เบรดทอล์ค']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('auntie_anne_s_original_pretzel','Auntie Anne''s','Original pretzel','อานตี้แอนส์เพรทเซล','bakery','1 piece',340,65,8,5,8,NULL,ARRAY['auntie anne','อานตี้แอนส์']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('texas_chicken_fried_chicken_1_pc','Texas Chicken','Fried chicken 1 pc','เท็กซัสชิกเก้นไก่ทอด 1 ชิ้น','fast_food','1 piece',300,12,20,20,1,NULL,ARRAY['texas chicken','เท็กซัสชิกเก้น']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('subway_6_inch_turkey_sandwich','Subway','6 inch turkey sandwich','ซับเวย์แซนด์วิช 6 นิ้ว','fast_food','6 inch',320,46,20,7,8,NULL,ARRAY['subway','ซับเวย์']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('mos_burger_cheeseburger','Mos Burger','Cheeseburger','มอสเบอร์เกอร์ชีสเบอร์เกอร์','fast_food','1 burger',360,35,18,17,8,NULL,ARRAY['mos burger','มอสเบอร์เกอร์']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('ootoya_chicken_kuroyaki_set','Ootoya','Chicken kuroyaki set','โอโตยะชุดไก่ย่าง','restaurant','1 set',700,85,35,22,10,NULL,ARRAY['ootoya','โอโตยะ']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('pepper_lunch_beef_pepper_rice','Pepper Lunch','Beef pepper rice','เปปเปอร์ลันช์บีฟเปปเปอร์ไรซ์','restaurant','1 plate',750,85,32,32,8,NULL,ARRAY['pepper lunch','เปปเปอร์ลันช์']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('sizzler_salad_bar_plate','Sizzler','Salad bar plate','ซิซซ์เลอร์สลัดบาร์ 1 จาน','restaurant','1 plate',350,30,18,18,10,NULL,ARRAY['sizzler','ซิซซ์เลอร์']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('bar_b_q_plaza_pork_grill_set','Bar B Q Plaza','Pork grill set','บาร์บีก้อนหมูกระทะชุดเล็ก','restaurant','1 set',750,60,42,38,12,NULL,ARRAY['bar b q plaza','บาร์บีก้อน']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('sukiya_gyudon_regular','Sukiya','Gyudon regular','สุคิยะกิวด้ง','restaurant','regular',650,90,28,20,12,NULL,ARRAY['sukiya','สุคิยะ']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('kouen_salmon_buffet_estimate','Kouen','Salmon buffet estimate','โคเอ็นแซลมอนบุฟเฟต์','restaurant','1 meal',900,60,55,50,12,NULL,ARRAY['kouen','โคเอ็น']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('gindaco_takoyaki_6_pcs','Gindaco','Takoyaki 6 pcs','กินดาโกะทาโกะยากิ 6 ลูก','snack','6 pcs',420,55,14,16,8,NULL,ARRAY['gindaco','กินดาโกะ','ทาโกะยากิ']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('mister_potato_chips_small','Mister Potato','Chips small','มิสเตอร์โปเตโต้ซองเล็ก','snack','1 small bag',120,13,2,7,1,NULL,ARRAY['mister potato','มิสเตอร์โปเตโต้']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('calbee_potato_chips_small','Calbee','Potato chips small','คาลบี้ซองเล็ก','snack','1 small bag',120,13,2,7,1,NULL,ARRAY['calbee','คาลบี้']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('jack_n_jill_roller_coaster_small','Jack ''n Jill','Roller Coaster small','โรลเลอร์โคสเตอร์ซองเล็ก','snack','1 small bag',120,18,2,5,3,NULL,ARRAY['roller coaster','โรลเลอร์โคสเตอร์']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('bento_squid_snack_small','Bento','Squid snack small','เบนโตะปลาหมึกซองเล็ก','snack','1 small bag',80,12,5,1,8,NULL,ARRAY['bento','เบนโตะ']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('mama_instant_noodles_pack','Mama','Instant noodles pack','มาม่าซอง','instant_food','1 pack',280,42,7,10,4,NULL,ARRAY['มาม่า','mama']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('wai_wai_instant_noodles_pack','Wai Wai','Instant noodles pack','ไวไวซอง','instant_food','1 pack',280,42,7,10,4,NULL,ARRAY['ไวไว','wai wai']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('nissin_cup_noodles','Nissin','Cup noodles','นิสชินคัพนูดเดิล','instant_food','1 cup',320,45,8,12,4,NULL,ARRAY['nissin','นิสชิน']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('vitamilk_soy_milk_bottle','Vitamilk','Soy milk bottle','ไวตามิ้ลค์','drink','1 bottle',160,28,7,3,20,NULL,ARRAY['ไวตามิ้ลค์','vitamilk']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('lactasoy_soy_milk_box','Lactasoy','Soy milk box','แลคตาซอย','drink','1 box',150,24,7,4,18,NULL,ARRAY['แลคตาซอย','lactasoy']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('milo_uht_box','Milo','UHT box','ไมโลกล่อง','drink','1 box',170,28,5,3,22,NULL,ARRAY['ไมโล','milo']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('ovaltine_uht_box','Ovaltine','UHT box','โอวัลตินกล่อง','drink','1 box',180,30,5,4,24,NULL,ARRAY['โอวัลติน','ovaltine']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false),
  ('yakult_bottle','Yakult','Bottle','ยาคูลท์','drink','1 bottle',50,12,1,0,10,NULL,ARRAY['ยาคูลท์','yakult']::text[],'estimate_seed','Initial PaeCal estimate seed; verify against label/official nutrition before marking verified.','medium','active',false)
on conflict (preset_key) do update set
  brand = excluded.brand,
  product_name = excluded.product_name,
  menu_name = excluded.menu_name,
  category = excluded.category,
  serving_size = excluded.serving_size,
  kcal = excluded.kcal,
  carb = excluded.carb,
  protein = excluded.protein,
  fat = excluded.fat,
  sugar = excluded.sugar,
  sweetness_level = excluded.sweetness_level,
  aliases = excluded.aliases,
  source_type = excluded.source_type,
  source_note = excluded.source_note,
  confidence = excluded.confidence,
  status = excluded.status,
  verified = excluded.verified,
  updated_at = now();

insert into public.drink_sweetness_levels (
  drink_key, menu_name, sweetness_level,
  kcal, carb, protein, fat, sugar,
  source_type, source_note, confidence, verified
) values
  ('thai_tea','ชาไทย',0,90,12,0,0,8,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('thai_tea','ชาไทย',25,130,20,0,0,16,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('thai_tea','ชาไทย',50,170,28,0,0,24,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('thai_tea','ชาไทย',75,220,35,0,0,30,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('thai_tea','ชาไทย',100,280,45,0,0,40,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('green_tea_milk','ชาเขียวนม',0,90,12,0,0,8,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('green_tea_milk','ชาเขียวนม',25,130,20,0,0,16,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('green_tea_milk','ชาเขียวนม',50,170,28,0,0,24,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('green_tea_milk','ชาเขียวนม',75,220,35,0,0,30,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('green_tea_milk','ชาเขียวนม',100,280,45,0,0,40,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('milk_tea','ชานม',0,120,12,0,0,8,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('milk_tea','ชานม',25,180,24,0,0,18,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('milk_tea','ชานม',50,240,36,0,0,28,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('milk_tea','ชานม',75,300,45,0,0,36,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('milk_tea','ชานม',100,360,56,0,0,46,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('americano','อเมริกาโน่',0,15,2,0,0,0,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('americano','อเมริกาโน่',25,40,10,0,0,8,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('americano','อเมริกาโน่',50,70,18,0,0,16,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('americano','อเมริกาโน่',75,100,26,0,0,24,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('americano','อเมริกาโน่',100,130,34,0,0,32,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('latte','ลาเต้',0,130,10,0,0,8,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('latte','ลาเต้',25,160,15,0,0,12,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('latte','ลาเต้',50,190,22,0,0,18,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('latte','ลาเต้',75,230,30,0,0,26,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('latte','ลาเต้',100,280,40,0,0,36,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('cocoa','โกโก้',0,140,15,0,0,8,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('cocoa','โกโก้',25,190,26,0,0,18,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('cocoa','โกโก้',50,240,36,0,0,28,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('cocoa','โกโก้',75,300,48,0,0,40,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('cocoa','โกโก้',100,360,60,0,0,52,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('lemon_tea','ชามะนาว',0,50,12,0,0,8,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('lemon_tea','ชามะนาว',25,90,22,0,0,18,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('lemon_tea','ชามะนาว',50,130,32,0,0,28,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('lemon_tea','ชามะนาว',75,170,42,0,0,38,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('lemon_tea','ชามะนาว',100,220,55,0,0,50,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('orange_juice','น้ำส้ม',0,80,20,0,0,16,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('orange_juice','น้ำส้ม',25,100,24,0,0,20,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('orange_juice','น้ำส้ม',50,120,28,0,0,24,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('orange_juice','น้ำส้ม',75,150,36,0,0,32,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false),
  ('orange_juice','น้ำส้ม',100,180,44,0,0,40,'estimate_seed','Initial sweetness estimate; tune by brand/label later.','medium',false)
on conflict (drink_key, sweetness_level) do update set
  menu_name = excluded.menu_name,
  kcal = excluded.kcal,
  carb = excluded.carb,
  protein = excluded.protein,
  fat = excluded.fat,
  sugar = excluded.sugar,
  source_type = excluded.source_type,
  source_note = excluded.source_note,
  confidence = excluded.confidence,
  verified = excluded.verified,
  updated_at = now();

-- Quick sanity checks after running:
-- select count(*) from public.brand_food_presets;
-- select count(*) from public.drink_sweetness_levels;
-- select brand, product_name, kcal, aliases from public.brand_food_presets where aliases && ARRAY['เลย์']::text[];
-- select * from public.drink_sweetness_levels where drink_key = 'thai_tea' order by sweetness_level;
